DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    customer JSONB NOT NULL,
    items JSONB NOT NULL,
    email TEXT, -- Added for easier filtering by user

    sub_total NUMERIC,
    shipping_fee NUMERIC,
    discount NUMERIC,
    total_amount NUMERIC,

    status TEXT DEFAULT 'pending',
    payment_method TEXT,
    payment_info JSONB
);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_all"
ON orders
FOR ALL
USING (true)
WITH CHECK (true);
