-- Create Vouchers table
create table if not exists public.user_vouchers (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  code text not null,
  discount_amount integer not null,
  min_order_value integer default 0,
  status text default 'active', -- active, used, expired
  created_at timestamp with time zone default timezone('utc'::text, now()),
  expires_at timestamp with time zone
);

alter table public.user_vouchers enable row level security;

create policy "Users can view own vouchers" on public.user_vouchers
  for select using (auth.uid() = user_id);

create policy "Users can insert own vouchers" on public.user_vouchers
  for insert with check (auth.uid() = user_id);
