-- 1. Create a table for public profiles
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  points integer default 0,
  last_lucky_spin timestamp with time zone,
  spin_tickets integer default 0,
  
  constraint username_length check (char_length(full_name) >= 3)
);

-- 2. Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- 3. Create a table for point history (transactions)
create table if not exists public.point_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  amount integer not null,
  reason text not null,
  type text check (type in ('earn', 'spend')) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.point_transactions enable row level security;

create policy "Users can view their own transactions." on public.point_transactions
  for select using (auth.uid() = user_id);

create policy "Users can insert their own transactions." on public.point_transactions
  for insert with check (auth.uid() = user_id);

-- 4. Create a trigger to auto-create profile on signup
-- This triggers when a new user is inserted into auth.users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, points)
  values (
    new.id, 
    new.raw_user_meta_data->>'full_name',
    200 -- Give 200 initial points as welcome bonus
  );
  
  -- Log the welcome bonus transaction
  insert into public.point_transactions (user_id, amount, reason, type)
  values (new.id, 200, 'Đăng ký thành viên', 'earn');
  
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- MIGRATION: Ensure columns exist for existing tables
alter table public.profiles 
add column if not exists last_lucky_spin timestamp with time zone,
add column if not exists spin_tickets integer default 0;

-- 5. Create Vouchers table
create table if not exists public.user_vouchers (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  code text not null,
  discount_amount integer not null,
  min_order_value integer default 0,
  status text default 'active', -- active, used, expired
  created_at timestamp with time zone default timezone('utc'::text, now()),
  expires_at timestamp with time zone
);

alter table public.user_vouchers enable row level security;

create policy "Users can view own vouchers" on public.user_vouchers
  for select using (auth.uid() = user_id);

create policy "Users can insert own vouchers" on public.user_vouchers
  for insert with check (auth.uid() = user_id);
