-- Migration: Create coupons table
-- Date: 2026-01-08

CREATE TABLE IF NOT EXISTS coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    discount_type TEXT NOT NULL CHECK (discount_type IN ('percent', 'fixed')),
    discount_value NUMERIC NOT NULL,
    min_order_value NUMERIC DEFAULT 0,
    max_discount_amount NUMERIC, -- Only relevant for 'percent' type
    start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    end_date TIMESTAMP WITH TIME ZONE,
    usage_limit INTEGER,
    used_count INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add comments
COMMENT ON COLUMN coupons.code IS 'The coupon code string (e.g. SUMMER2024)';
COMMENT ON COLUMN coupons.discount_type IS 'Type of discount: percent or fixed amount';
COMMENT ON COLUMN coupons.discount_value IS 'Value of discount (e.g. 10 for 10% or 50000 for 50k)';

-- Insert initial sample coupons
INSERT INTO coupons (code, discount_type, discount_value, min_order_value, start_date, end_date)
VALUES 
('HKTSHOES', 'percent', 10, 0, NOW(), NOW() + INTERVAL '1 year'),
('GIAM50K', 'fixed', 50000, 200000, NOW(), NOW() + INTERVAL '1 year'),
('JOY', 'fixed', 200000, 1000000, NOW(), NOW() + INTERVAL '1 year')
ON CONFLICT (code) DO NOTHING;
